Import libraries

In [1]:
import numpy as np 
import matplotlib.pyplot as plt
import pandas as pd

Import data

In [2]:
dataset = pd.read_csv('Data.csv')

In [3]:
x = dataset.iloc[:,:-1].values # convert to numpy array 
y = dataset.iloc[:,-1].values
print(x)
print(y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


<h2 style="color:RGB(223, 207, 190)">Working with missing data</h2>

In [4]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values=np.nan, strategy= 'mean') # create object allows replace NaN by mean value
imputer.fit(x[:,1:]) # select all rows and all number columns
x[:, 1:] = imputer.transform(x[:,1:])

In [5]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


<h2 style="color:RGB(223, 207, 190)">Encoding categorical data</h2>

In [6]:
# Encoding independent
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

# ColumnTransformer(transformers = [('encoder', fn to encoder, column ex: [0,1])], remainder='passthrough')
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [7]:
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [8]:
# Encoding label 
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [9]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


<h2 style="color:RGB(223, 207, 190)">Split into training and test</h2>

In [10]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state =1)

In [11]:
print(x_train.shape) # 8 samples

(8, 5)


In [12]:
print(x_test.shape) # 2 samples

(2, 5)


<h2 style="color:RGB(223, 207, 190)">Feature Scaling</h2>

In [13]:
# Standardization
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
x_train[:, 3:] = scaler.fit_transform(x_train[:, 3:])
x_test[:, 3:] = scaler.transform(x_test[:, 3:])

In [14]:
print(x_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [16]:
# Understanding StandardScaler 
sc = StandardScaler()
data = [[0,0],
        [0,0],
        [1,1],
        [1,1]]
print(sc.fit_transform(data))

[[-1. -1.]
 [-1. -1.]
 [ 1.  1.]
 [ 1.  1.]]


In [17]:
# now sc object has properties mean_ and scale_ 
print(sc.mean_, sc.scale_)

[0.5 0.5] [0.5 0.5]


In [18]:
# transform with sc object 
print(sc.transform([[2,2]]))

[[3. 3.]]
